# Generated by Django 4.2 on 2025-09-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('campaign_name', models.CharField(max_length=255)),
                ('ad_group_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conversions', models.PositiveIntegerField()),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ctr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Data',
                'verbose_name_plural': 'Promotional Data',
                'ordering': ['-date'],
            },
        ),
    ]
