# Generated by Django 4.2 on 2025-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='variant_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
