# Generated by Django 4.2 on 2025-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0002_promotionaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='generated_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
