# Generated by Django 4.2 on 2025-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0003_prompt_generated_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
