# Generated by Django 4.2 on 2025-09-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0003_remove_order_customer_remove_order_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
