# Generated by Django 4.2 on 2025-09-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0004_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location_id',
        ),
    ]
