# Generated by Django 4.2 on 2025-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0005_collection_remove_prompt_type_collectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='image_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
