# Generated by Django 4.2 on 2025-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0006_collectionitem_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
