# Generated by Django 4.2 on 2025-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0010_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionaldata',
            name='cpc',
        ),
        migrations.RemoveField(
            model_name='promotionaldata',
            name='roas',
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='avg_cpc',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='conv_value_per_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='cost_per_conversion',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='currency_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldata',
            name='variant_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaldata',
            name='ad_group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaldata',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaldata',
            name='conversion_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaldata',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaldata',
            name='ctr',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
