# Generated by Django 4.2 on 2025-09-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0011_remove_promotionaldata_cpc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionaldata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApplication.companyuser'),
        ),
    ]
