# Generated by Django 4.2 on 2025-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0012_alter_promotionaldata_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionaldata',
            name='ad_group_name',
        ),
        migrations.RemoveField(
            model_name='promotionaldata',
            name='campaign_name',
        ),
        migrations.AlterField(
            model_name='promotionaldata',
            name='variant_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
