# Generated by Django 4.2 on 2025-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0013_remove_promotionaldata_ad_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionaldata',
            name='variant_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
