# Generated by Django 4.2 on 2025-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0014_alter_promotionaldata_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_id',
            field=models.CharField(max_length=100),
        ),
    ]
