# Generated by Django 4.2 on 2025-09-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('img', models.URLField(blank=True, null=True)),
                ('trend', models.FloatField(blank=True, null=True)),
                ('FC7', models.FloatField(blank=True, null=True)),
                ('FC30', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('on_order', models.IntegerField(default=0)),
                ('reorder', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('action_item', models.TextField(blank=True, null=True)),
                ('week_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
