# Generated by Django 4.2 on 2025-09-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0010_alter_purchaseorder_delivery_date_and_more'),
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryprediction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CoreApplication.companyuser'),
        ),
        migrations.AlterField(
            model_name='inventoryprediction',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApplication.productvariant'),
        ),
    ]
