# Generated by Django 4.2 on 2025-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_inventoryprediction_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryprediction',
            name='FC30',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryprediction',
            name='FC7',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
