# Generated by Django 4.2 on 2025-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0003_alter_inventoryprediction_fc30_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryprediction',
            name='last_30_days_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryprediction',
            name='last_7_days_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryprediction',
            name='trend',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
