# Generated by Django 4.2 on 2025-09-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0004_inventoryprediction_last_30_days_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryprediction',
            old_name='last_30_days_quantity',
            new_name='last30',
        ),
        migrations.RenameField(
            model_name='inventoryprediction',
            old_name='last_7_days_quantity',
            new_name='last7',
        ),
    ]
