# Generated by Django 4.2 on 2025-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0005_rename_last_30_days_quantity_inventoryprediction_last30_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryprediction',
            name='sku',
            field=models.CharField(max_length=255),
        ),
    ]
