# Generated by Django 4.2 on 2025-09-22 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoreApplication', '0014_alter_promotionaldata_variant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUForecastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('predicted_sales', models.IntegerField()),
                ('actual_sales', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('error', models.IntegerField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApplication.companyuser')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
