# Generated by Django 4.2 on 2025-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testingproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skuforecasthistory',
            old_name='actual_sales',
            new_name='actual_sales_30',
        ),
        migrations.RenameField(
            model_name='skuforecasthistory',
            old_name='predicted_sales',
            new_name='predicted_sales_30',
        ),
        migrations.AddField(
            model_name='skuforecasthistory',
            name='predicted_sales_60',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skuforecasthistory',
            name='predicted_sales_90',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
