# Generated by Django 4.2 on 2025-10-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testingproject', '0002_rename_actual_sales_skuforecasthistory_actual_sales_30_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuforecasthistory',
            name='live_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
