# Generated by Django 4.2 on 2025-10-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0014_alter_promotionaldata_variant_id'),
        ('Testingproject', '0003_skuforecasthistory_live_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_valuations', to='CoreApplication.companyuser')),
            ],
            options={
                'verbose_name': 'Inventory Valuation',
                'verbose_name_plural': 'Inventory Valuations',
                'ordering': ['-month'],
            },
        ),
    ]
