# Generated by Django 4.2 on 2025-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testingproject', '0004_inventoryvaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvaluation',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
