# Generated by Django 4.2 on 2025-10-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApplication', '0014_alter_promotionaldata_variant_id'),
        ('Testingproject', '0005_inventoryvaluation_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUForecastMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.DateField()),
                ('forecast_accuracy', models.FloatField(blank=True, null=True)),
                ('forecast_bias', models.FloatField(blank=True, null=True)),
                ('days_of_inventory', models.FloatField(blank=True, null=True)),
                ('sell_through_rate', models.FloatField(blank=True, null=True)),
                ('inventory_turnover', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApplication.companyuser')),
            ],
            options={
                'unique_together': {('company', 'sku', 'month')},
            },
        ),
    ]
